### ISSUE TITLE
Check unused vertices for geometry of type MultiPoint and MultiLineString

### ISSUE THREAD

**Issue by gperonato** [cityjson/cjval#5]
Hello, it looks likes that the validator only checks for unused vertices of type "MultiSurface", "CompositeSurface", "Solid", "MultiSolid" and "CompositeSolid".
Is there any reason not to include also "MultiPoint" and "MultiLineString"?
This is would helpful when using extensions.

**Comment by hugoledoux** [comment]
oh wow indeed, I forgot that, also for `wrong_vertex_index()`

I'll fix this soon and make a new release, cheers for pointing this out 👍

**Comment by gperonato** [comment]
Thanks a lot!

**Comment by hugoledoux** [comment]
fixed in a3c5803e1d9cbdd41bbb0251f1c2e8ee194b4bc9 2d013c9bfbcf9b380ee4cea76a1cddd2205299e9 3f8ace540ae8fe28311bc8b26ba274a6d2a3413c

Will be merge to main soon and will be in v0.4.1 (after I fixed the semantics checks, there I also omitted points and lines...)

**Comment by clausnagel** [comment]
I also get an unused vertices warning for the reference points of template geometries with cjval 0.4 (actually, I am using the [web validator](https://validator.cityjson.org/)). Is this related to the above and also already fixed by your commits?

Test dataset: [SolitaryVegetationObject.zip](https://github.com/cityjson/cjval/files/7882372/SolitaryVegetationObject.zip)

**Comment by hugoledoux** [comment]
thanks @clausnagel this wasn't the exact same error but another one in that function. I guess I wrote this function on a bad day... pfff

Now fixed, in branch main, will be in v0.4.1 soon (also online).
