### ISSUE TITLE
Warnings not visible when there is an error

### ISSUE THREAD

**Issue by ozgetufan** [cityjson/cjval#7]
I realised that when there is an error in a CityJSON file, cjval only outputs the error and not the warnings about that file. Only when the error is fixed, the warnings are outputted. Wouldn't it be better if it was possible to see both errors and warnings at the same time?

**Comment by hugoledoux** [comment]
I don't try to validate for the warnings if there are errors.

The reason is that an invalid file could make the function to check for errors crash or return false warnings that are there because the file is badly structured (aka "cascading effects").

So better this way (to avoid crashes), although I can imagine it's more iterative.

Also, if the schema is not okay (1st step), then some of the errors (eg wrong vertex indices) are not tested, for the same reason as above.
